config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users

  root                'static_pages#home'

  resources :boards


    resources :posts do
      member do
        put "like", to: "posts#upvote"
        put "dislike", to: "posts#downvote"
        get "vote_count", to: "posts#vote_count"
      end
    end


end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :posts

  def board_name
    self.board.name
  end

  def score
  self.get_upvotes.size - self.get_downvotes.size
end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :board
  belongs_to :user
  acts_as_votable

  def board_name
    self.board.name
  end

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts
# has_many :posts, through: :boards
acts_as_voter


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :authenticate_user! 

after_action :verify_authorized, unless: :devise_controller?

rescue_from Pundit::NotAuthorizedError do |e|
   flash[:danger] = "You don't have permissions for this request"
   redirect_to root_path
 end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  skip_after_action :verify_authorized
  skip_before_action :authenticate_user!
  before_action :set_user, except: [:destroy, :index, :edit, :update]

  def index
    @board = Board.all
  end

  def new
    authorize @user
    @board = Board.new
    # authorize @board
  end

  def show
    @board = Board.find params[:id]
  end

  def create
  @board = Board.new(name: params[:board][:name])
  if @board.save
    flash[:success] = "That Board is created!"
    #do something other then this. I just wanted to make sure it works :stuck_out_tongue:
    redirect_to @board
  else
    render :new
  end
end

def destroy
  authorize @user
  @board = Board.find params[:id]
  # authorize @board
  @board.destroy
  redirect_to "/boards"

end

private

def set_user
  @user = current_user
end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_list, only: [:new, :create]
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_after_action :verify_authorized

  def index
    @post = current_user.posts
    # authorize @post
  end

  def new
    @post = current_user.posts.new
    @board = Board.find(params[:board][:board_id])
  end

  def create
    @board = Board.find(params[:post][:board_id])
    @post = @board.posts.new approved_params
    # authorize @post
    if @post.save
      flash[:notice] = "Post created!"
      redirect_to @board
    else
      render :new
    end
  end


  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find params[:id]
    # authorize @board
    @post.destroy
    redirect_to "/boards"
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { count: @post.get_upvotes.size } }
    end
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    respond_to do |format|
      format.html {redirect_to :back }
      format.json { render json: { count: @post.get_downvotes.size } }
    end
  end

    def vote_count
      @post = Post.find(params[:id])
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { render json: { count: @post.score } }
      end
    end


    private

    def approved_params
      params.require(:post).permit(:title, :content, :board_id, :user_id)
    end



  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  skip_after_action :verify_authorized, only: [:home]


  def home
    # if logged_in?
    #   @micropost  = current_user.microposts.build
    #   @feed_items = current_user.feed.paginate(page: params[:page])
    # end
  end

  def boards
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.erb
<% provide(:title, 'Edit your Board') %>
<h1>Edit your board</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @board, url: edit_board_path do |f| %>

      <%= f.label :name%>
      <%= f.text_field :name, class: 'form-control' %>

      <button class="btn btn-primary">Post</button>
    <% end %>
  </div>
</div>

app/views/boards/index.html.erb
</table>
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

  <div class="table-responsive">
    <h2>Your Boards</h2>
    <p><%= link_to "Add a Board", new_board_path %></p>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <% @board.each do |board| %>
        <tr class="active">
          <td><%= board.name %></td>
          <td>
            <%= link_to "See Board", board_path(board), class: "btn btn-default btn-xs" %>
            <%= link_to 'Update', edit_board_path(board), class: "btn btn-default btn-xs" %>
            <%= link_to 'Delete', board_path(board), method: :delete, class: "btn btn-default btn-xs" %>
            <%end%>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

</body>
</html>

app/views/boards/new.html.erb
<% provide(:title, 'Make a new Board') %>
<h1>Post Message</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @board, url: boards_path do |f| %>

      <%= f.label :name%>
      <%= f.text_field :name, class: 'form-control' %>

      <button class="btn btn-primary">Post</button>
    <% end %>
  </div>
</div>

app/views/boards/show.html.erb
<h2><%= @board.name%></h2>
<%= form_for @board, url: new_post_path, method: :get do |f| %>
<%= f.hidden_field :board_id, value: @board.id %>
<button class="btn btn-primary">Write a Post</button>
<% end %>


<% @board.posts.each do |post| %>
<div class="well well-lg">
  <tr class="active">
    <p>Title:</p>
    <td><%= post.title %></td>
    <p>Content:</p>
    <td class="well well-lg"><%= post.content %></td>
    <div>
      <%= link_to 'Delete', post_path(post), method: :delete, class: "btn btn-default btn-xs" %>


      <div id="new-counter">

        <p class="result"></p>

         <!-- <span class= "like-<%= post.id %>"> -->
        <button class="btn btn-primary" id="add" data-post-id = "<%= post.id %>">+</button>
        <%= link_to like_post_path(post), method: :put, remote: true, class: 'like' do %>
        <%end%>

        <!-- <span class= "dislike-<%= post.id %>"> -->
        <button class="btn btn-primary" id="sub" data-post-id = "<%= post.id %>">-</button>
        <%= link_to dislike_post_path(post), method: :put, remote: true, class: 'dislike' do %>
        <%end%>

        <button class="btn btn-primary" id="reset">Reset</button>
        <button class="btn btn-primary" id="clearlog">Clear Log</button>
        <ul class="vote-list"></ul>

      </div>

      </div
    </tr>
  </div>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Redidit" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Redidit</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Boards", boards_path %></li>
            <li><%= link_to "New Board", new_board_path %></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to "Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-md-3">
          <div class="well sidebar-nav">
            <h3>ShortCuts</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Create a board", new_board_path   %></li>
              <li><%= link_to "Edit your account", edit_user_registration_path  %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <% if Rails.env.development? %>
          <p><%= params[:controller] %>#<%= params[:action] %></p>
        <% end %>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Post Message</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="container">

    <form role="form">
      <div class="form-group">
        <h1>Post Message</h1>

        <div class="row">
          <div class="col-md-6 col-md">
            <%= form_for @post, url: new_post_path(@post) do |f| %>
            <%= f.label :title%>
            <%= f.text_field :title, class: 'form-control' %>
          <textarea class="form-control" rows="5" id="comment" style = "margin: 5px;"></textarea>
          <button class="btn btn-primary">Post</button>

            <% end %>
          </div>
        </div>

      </div>
    </form>
  </div>

  </body
  </html>

app/views/posts/index.html.erb
<table class="table table-hover table-striped table-condensed">
  <h2>Your Posts</h2>

  <%= link_to "Add a Post", new_post_path %>

  <ul>
    <% @post.each do |list| %>
      <li>
        <%= link_to post.title, post %>

        <%= link_to "X", list, method: :delete %>
      </li>
    <% end %>
  </ul>
</table>

app/views/posts/new.html.erb
  <% provide(:title, 'Make a new Board') %>
  <h1>Post Message</h1>

  <div class="row" style = "margin: 5px;">
    <div class="col-md-6 col-md">
      <%= form_for @post, url: posts_path do |f| %>

        <%= f.label :title%>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :content%>
        <%= f.text_field :content, class: 'form-control' %>
        <%= f.hidden_field :board_id, value: @board.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>

        <button class="btn btn-primary">Post</button>
      <% end %>
    </div>
  </div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Redidit</h1>

  <h2>
    This is the home page for you boards
  </h2>
</div>